### PR TITLE
Nano editor as bin

### PR DESCRIPTION
**Pull request by RoboMario**
Cross complied Nano editor to add to bin

### CODE REVIEW

**Comment by jmtatsch** [comment]
Hi mario,

thank you for contributing my favorite editor.
We do not accept binary pull request for security reasons.
Can you please make a PR with a build recipe at https://github.com/Dafang-Hacks/Main ?
I will compile it then and check it in here.

**Comment by RoboMario** [comment]
> Hi mario,
> 
> thank you for contributing my favorite editor.
> We do not accept binary pull request for security reasons.
> Can you please make a PR with a build recipe at https://github.com/Dafang-Hacks/Main ?
> I will compile it then and check it in here.

Done that !

**Comment by timstanley1985** [comment]
+1 for this!!  I can never make head nor tail of vim so always use nano.  I tried cross compiling this a couple of weeks ago but got in a mess trying to cross compile lib-ncurses so gave up.

Am using your binary for now though so thanks for uploading!

**Comment by jmtatsch** [comment]
@RoboMario I have trouble to get nano to compile due to missing ncurses. Can you have a look at your PR again?

**Comment by timstanley1985** [comment]
Am having another go at trying to get ncurses to compile now.... wish me luck :-)

**Comment by jmtatsch** [comment]
https://github.com/Dafang-Hacks/Main/pull/83

**Comment by RoboMario** [comment]
> @RoboMario I have trouble to get nano to compile due to missing ncurses. Can you have a look at your PR again?

Sorry busy with other projects, but I will figure out how to reproduce the library issues and add this to the nano compile script to have the compile environment right for it

**Comment by timstanley1985** [comment]
@RoboMario @jmtatsch Dafang-Hacks/Main#84

**Comment by jmtatsch** [comment]
added in 8065bd58b57170aebe4951c42f742e0fa834a6c6

**Comment by jmtatsch** [comment]
Thanks @RoboMario and @timstanley1985

**Pull request closed without merging**
