### PR TITLE
Some cleanup in detectionOn.sh

### PR DESCRIPTION
**Pull request by c---**
* Change spaces to tabs
* Reformat some spacing
* Redo the logic that determines when to record video. This fixes an issue
where it would always record video even if Telegram was deactivated
* Fix FTP video record so it doesn't try to record twice

### CODE REVIEW

**Comment by jmtatsch** [comment]
Is the ftp streaming not worth keeping?

**Comment by c---** [comment]
You're right, I was too hasty in my search for unification. I wish more types could stream. I reverted my change to the FTP video recording so the current pull request should reflect that.

**Comment by jmtatsch** [comment]
Can you please resolve the conflicts?

**Comment by c---** [comment]
Merged. It's all cosmetic changes, no code changes. Mostly fixing spacing, some grammar, and 80-column stuff.

**Pull request merged**
