### PR TITLE
[UI] Control service change to toggle

### PR DESCRIPTION
**Pull request by gysmo38**
Change service control to toggle button.
I also re write cgi to be more efficient, for that I need to rename onvif control script to remove .sh on his name.

@jmtatsch Not yet found a way to have the theme color on it. So I let it green.

### CODE REVIEW

**Comment by gysmo38** [comment]
I also update rtsp-h264 et rtsp-mjpeg script to change pid filename from v4l2server....pid to rtsp-h264.pid and rtsp-mjpeg.pid
All controlscripts have same way to name pid file.

**Comment by jmtatsch** [comment]
More consistency is always nice. And ui_control.cgi is so much leaner.

**Comment by jmtatsch** [comment]
Hmm, the stati of the services are not read correctly for me.
Screenshot 2020-06-07 at 22 15 37Everything appears stopped although some are undoubtetly running.
Also can you make the play/stop button just one round button that is replaced upon click by its counterpart?

**Comment by gysmo38** [comment]
@jmtatsch strange. I remove buttons start/stop. It is now toggle button. I will check tomorrow what happen.

**Comment by Combie81** [comment]
Yeah I noticed that - i started a fresh install/config and works fine.
Sadly all the spaces are back :P

**Pull request merged**
