### PR TITLE
Bring beta up to date

### PR DESCRIPTION
**Pull request by jmtatsch**

### CODE REVIEW

**Comment by nik0** [comment]
Great !!!

**Comment by jmtatsch** [comment]
Haha, sorry for all this mess.

**Comment by nik0** [comment]
It’s not me that will say something 😜

**Comment by jmtatsch** [comment]
Anyhow, thanks a lot for making the rtspserver work great again :)
Did you check in all the changed sources as well?
Maybe the HLS streaming works better now, i will give it a shot...

**Comment by nik0** [comment]
Yes everything is committed...

**Comment by jmtatsch** [comment]
Hmm, 
Flag -S is set
server is sending
send file:index.html
send file:hls.light.min.js
But still no HLS stream

**Comment by nik0** [comment]
How do you check that ?
I tested with VLC and it seemed to work

**Comment by jmtatsch** [comment]
just http://yourip:8554

**Comment by nik0** [comment]
With which browser ?

**Comment by jmtatsch** [comment]
Safari is supposed to have native support. Tried firefox as well.

**Pull request merged**
