### PR TITLE
new ui proposal

### PR DESCRIPTION
**Pull request by gysmo38**
A proposal of a new UI.
It is not finish. I am working on it.
I juste made this PR if some users want to test it and give me feedback.
The idea is to have something more unified. I switch from bulma to w3.css.
I found it more comprehensive and light.
You can try without break actual ui. To test just go to index2.html
There is a lot of files due to fontawesone. I will reduce it at the end.

### CODE REVIEW

**Comment by jmtatsch** [comment]
Can you maybe make some sneak preview screenshots for us lazy ones?

**Comment by gysmo38** [comment]
Sure :)
Main Page
image

Main page with camera control
image

Example page (information)

image

**Comment by nik0** [comment]
Another proposition is to add your GUI as a new theme (new link at the bottom of the main page)
We can all test it and then we will decide which one we keep
What do you think ?

**Comment by gysmo38** [comment]
Yes a good idea. It easy because I create an index2.html 
I also rewrite all pages to have same structure (html + js + cgi)
It is a lot of work I don't known how many it will take me to finish.
Already done: Main page, camera control, switch control and system configuration.

**Comment by nik0** [comment]
You can not have a separate folder? All links are absolute ?

**Comment by gysmo38** [comment]
No absolute link :(

**Comment by lech4tnoir** [comment]
Cool :D

**Comment by gysmo38** [comment]
@jmtatsch If you want you can merge it, it will break nothing. I add a link at the bottom of each ui to switch between them. My new ui is not finish but you can control your camera, use control buttons, and configure it.
I have to finish services, update and status

**Comment by Benouzao** [comment]
This looks really nice, well done.
Have you tried the new GUI from a phone browser? The current one has some display issues using a phone browser.
Thanks

**Comment by gysmo38** [comment]
Yes, this one of the reason why I started rewrite GUI.
It should work well on smartphone. I tested on my S9, it work pretty well.

**Comment by gysmo38** [comment]
I finish my first release of new UI. I hope you will enjoy it.
If you like it, I plan to add more features: color themes, login page, mqtt config page, notification config page (eg telegram and mail)

**Comment by gysmo38** [comment]
@jmtatsch I will add improvement but you can merge this PR. It break nothing, I add a link to switch between UI.

**Comment by jmtatsch** [comment]
Do we need all 1700 files of that framework?

**Comment by gysmo38** [comment]
No I just use somes icons. I will reduce the size.

**Comment by gysmo38** [comment]
It should be better :)

**Pull request merged**
