### PR TITLE
Fix cover definition in mqtt autodiscovery for HA 0.82+

### PR DESCRIPTION
**Pull request by mikeage**

### CODE REVIEW

**Comment by mikeage** [comment]
Closes #787

**Comment by jmtatsch** [comment]
Does this already work?

**Comment by jmtatsch** [comment]
Thanks for fixing this.

**Comment by badabing2005** [comment]
Please see [here](https://github.com/home-assistant/home-assistant/issues/18354)
As it seems to still be problematic.

Thanks
BB

**Pull request merged**
