### PR TITLE
Onvif Service

### PR DESCRIPTION
**Pull request by Sian-Lee-SA**
Created an Onvif service that allows PTZ Control (including presets), Resolution Changes, FPS changes Stream URI and Snapshot URI. 

Currently auto discovery hasn't been implemented as of yet but can be added easily by using the port (default: 8080) and ip of the camera.

A startup script has been added which can start and stop the service via the web interface. This has been tested on Synology Surveillance Station and works quite well. Listening port can be changed by using the --port flag.

### CODE REVIEW

**Comment by jmtatsch** [comment]
Amazing!
Many people have been hoping for onvif support for a long time.
Unfortunately, for security reasons, we do not accept binary pull requests.
Could you please also contribute the source code and a build script for onvif_srvd at https://github.com/Dafang-Hacks/Main ?

**Comment by CQoute** [comment]
> Could this file be renamed to something more meaningful like camera_position_presets.conf

I was thinking this at the moment I committed. But I will update the file name. Was thinking ptz_presets.conf?

Not going to lie, the whole process has been a head scratcher considering the lack of documentations and examples involving onvif code. In the end I learnt a lot and as I was browsing the issues, I had noticed the request for ptz support and figured this service would help those out who wish to use ptz via onvif.

With that said, the code is still a bit premature and maybe a little tailored for my own environment but I had a sudden urge to offer this function based on high demand...

I just forked https://github.com/Dafang-Hacks/Main and will commit the source code after I clean somethings up then will initiate a pull request.

**Comment by sedony23** [comment]
This is extraordinary. Thanks Sian! It would be great, if this could be integrated in the official tree!

**Comment by Sian-Lee-SA** [comment]
This has been pushed in the Main repo https://github.com/Dafang-Hacks/Main/pull/41

**Comment by jmtatsch** [comment]
Defaults credentials seem to be root/password on port 8080

**Comment by mitchoklemen** [comment]
Sian Thak you very much!!

**Comment by LiloBzH** [comment]
Thank you ! :)

**Comment by Benouzao** [comment]
This is great, super excited about this one!
Is there plan to add configuration capability to change pwd and port?
Could not check yet, but can anyone confirm audio is working?
Thanks

**Comment by uski** [comment]
This is great. Any plan for motion detection through onvif ? I believe the camera can notify the NVR when motion is detected, so that the NVR can do recording only during motion detection.
At least the notification could be implemented, but it would also be possible to change the motion detection settings in the camera through ONVIF, as a future stage.

**Comment by throttlenerd** [comment]
This is sooo great! Thank you guys!!!!

**Comment by throttlenerd** [comment]
Hey guys, just in case it could be helpful: I toggled Autorun on for onvif-srvd.sh, but even though camera stream via ONVIF works on my Synology NAS, PTZ controls, if I reboot the camera, do not. If, after the camera boots up, I manually stop onvif-srvd.sh and then start it again -- PTZ works.

Xiaomi Dafang with latest soft from Elias
Synology DS218j, all apps/OS up-to-date

**Comment by dave-code-ruiz** [comment]
Great job! Amazing result on my nvr, Any plan for motion detection through onvif ? I believe the camera can notify the NVR when motion is detected, so that the NVR can do recording only during motion detection

**Pull request closed without merging**
