### PR TITLE
Rebased on latest version on https://github.com/mpromonet/v4l2rtspserver …

### PR DESCRIPTION
**Pull request by nik0**
- No more memory leak (hopefully)
- latest version of live555

### CODE REVIEW

**Comment by jmtatsch** [comment]
Still running strong after 21 hours. I think that did it!
Not sure where the conflict in this PR comes from, can you fix it easily or should I just manually check in the binaries from your beta branch?

**Comment by nik0** [comment]
Get the latest commited version of openRTSP

**Comment by jmtatsch** [comment]
I don't fully understand. I would just cherrypick https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/1403/commits/41f1540b1e04a142bc294a0cb1c1e616c6fb004c as it has your latest openRTSP. Correct?

**Comment by nik0** [comment]
Yes, correct

**Comment by jmtatsch** [comment]
Okay, its cherrypicked. Thanks for looking into this, very much appreciated!

**Pull request closed without merging**
