### PR TITLE
Adding exposure + MQTT-config var LIGHT_SENSOR

### PR DESCRIPTION
**Pull request by exetico**
As discussed in https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/1165, i guess this will be the best thing to do.

Kindly secure logics is as you would like it?

### CODE REVIEW

**Comment by jmtatsch** [comment]
Looks great. Thank you very much.

**Comment by exetico** [comment]
@jmtatsch  - I just updated, but there's no image from the camera.
image

Is there another issue? (No image from webinterface, Home-Assistant).

Also, no data at `sw_night_configure.html`:
image

**Comment by jmtatsch** [comment]
Did you restart your camera? also make sure your rtsp service is running.
with no data in auto_night tuning there is another open issue.

**Comment by exetico** [comment]
Oh well, spot on. `rtsp-h264` did not turn on after i rebooted the device, however, `Autorun` **is** enabled for the service?

After manually pressing 'Start`, a PID was provided, and it worked again.

Yet another bug, or? :-)

**Comment by jmtatsch** [comment]
Usually it works, sometimes it doesn't.

**Pull request merged**
