### PR TITLE
Modify detectionOn script to use optimized jpeg instead

### PR DESCRIPTION
**Pull request by atiti**
This patch adds a new command which acquires and optimizes an image from
the camera. It also modifies the detectionOn.sh script to use the
optimized jpeg, thereby reducing the space need, and the wear on the
microsd card.

### CODE REVIEW

**Comment by saipsa** [comment]
It should be optional based on configuration parameter.

**Comment by nik0** [comment]
`--stdin` option ?
Or use jpegtran
`/system/sdcard/bin/getimage |  /system/sdcard/bin/jpegtran -progressive -optimize`

**Comment by M0ebiu5** [comment]
It only works here, if i change the shell:
#!/bin/bash -> #!/bin/sh

**Comment by Dopeyr** [comment]
@atiti You may be able to close this now, as in the latest firmware `/system/sdcard/bin/getimage` returns a much smaller, already compressed image.

e.g. 

Old firmware
---

```
MBP~ % ssh root@192.169.1.221 '/system/sdcard/bin/getimage|wc -c'
1440000
```

New firmware
---

```
MBP~ % ssh root@192.169.1.220 '/system/sdcard/bin/getimage|wc -c'
171167
```

So it's now roughly 10% the size.

**Comment by atiti** [comment]
Great, then this is not needed :)

**Pull request closed without merging**
