### PR TITLE
Howto unbrick

### PR DESCRIPTION
**Pull request by lukeIam**
Some instructions how to unbrick the camera based on my experiences.
(I was able to unbrick my camera with those offsets)

### CODE REVIEW

**Comment by EliasKotlyar** [comment]
Many thanks @lukeIam !

**Comment by saipsa** [comment]
@lukeIam Will this work if I have bricked uboot? can I flash uboot.bin using this method?

**Comment by lukeIam** [comment]
> Will this work if I have bricked uboot? can I flash uboot.bin using this method?

Hi @saipsa,

I haven't tried - but an long an your uboot is still booting you could give it a try.

**Comment by saipsa** [comment]
@lukeIam Actually my uboot is not booting. 

I bricked while flashing uboot.bin https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/30

It said 513+0 records in but 512+0 records out, and something along the lines of,

memory full/no space available. cannot write.

So according to my understanding uboot is not booting. 

---

The status lines and command prompt will appear only if uboot is booting, and I can't use your method, if uboot is not booting? 

I am asking as I will have to purchase the FTDI adapter and soldering equipment.

**Comment by EliasKotlyar** [comment]
@lukeIam : I tried this unbrick instructions today, and was able to recover my dead dafang. There was only a small change needed to make it work. Great work, thanks!

**Comment by ronnyandre** [comment]
What to do if the serial doesn't read anything?

**Pull request merged**
