### PR TITLE
Allow custom firmware repositories

### PR DESCRIPTION
**Pull request by xdissent**
This adds custom repository support to autoupdate.sh and the web update UI. The repo is stored in the VERSION file and defaults to your repo. (Should be safe for existing installs)

### CODE REVIEW

**Comment by jmtatsch** [comment]
Also looks great. Please also against beta.

**Comment by xdissent** [comment]
OK, this and all the others have been updated. There will be some conflicts I'll fix as the PRs get merged. Thanks!

**Comment by jmtatsch** [comment]
Ok, once the conflicts are resolved this can be merged as well.

**Comment by xdissent** [comment]
Updated!

**Pull request merged**
