### PR TITLE
Audio inputs modifications

### PR DESCRIPTION
**Pull request by nik0**
**Please test before merging** 
Audio modifications
         * Several codecs are now available: MP3 (default), OPUS, RAW PCM and PCU ulaw
                use the folowing typical commands
                  - /system/sdcard/bin/v4l2rtspserver-master MP3:44100:44100
                  - /system/sdcard/bin/v4l2rtspserver-master OPUS:48000:48000
                  - /system/sdcard/bin/v4l2rtspserver-master PCM:8000:8000
                  - /system/sdcard/bin/v4l2rtspserver-master PCMU:8000:8000
    
         * Setconf can now control volume and filering
                'h' set hardware volume (from mic)
                'i' set software volume percentage (X will add X44 the data, from 0 to xxx, -1 to do nothing)
                'q' set set filter number (1 or 2, 0 no filter)

### CODE REVIEW

**Comment by sanderdh** [comment]
Thank you I had no sound at all. So to test this PR I copied the setconf and v4l2rtspserver-master binaries to the sdcard and started v4l2rtspserver-master with -E PCM:8000:8000  (Did you forget -E in the examples in this PR?) and ran setconf -k h -v 30.
I can now finally hear the audio using the audio test from the settings menu, however there is a lot of static noise when I use setconf with a value for h above 10. Using option q with value 1 resolves the noise issue however the audio volume is still quite low. What are the ranges for the setconf i and h options, max 999? The audio also breaks up a bit but maybe that has to do with wifi quality?
Any other codec then PCM did not work.

**Comment by nik0** [comment]
Thanks for the feedback.
Yes you need the -E options
When you don't have audio, what VLC say about the audio codec, the number of audio packets received.

Yes there is a lot of static noise, the mic is poor quality, in the original API you can not go higher than 8000.  
I don't know exactly the higher limit of the H/W volume. But try 100 or 130 as values

**Comment by sanderdh** [comment]
VLC states:
Stream 1
 Codec: MPEG Audio layer 1/2 (mpga)
 Type: Audio

It states it Decodes blocks but Played 0 buffers and Lost 0 buffers.
I wonder why for some people it seems to work without your fixes, different hardware versions perhaps? Maybe I should add I have never had the camera run with the original firmware.

**Comment by nik0** [comment]
It is the same if you don't specify any -E options ?

**Comment by sanderdh** [comment]
If I use the v4l2rtspserver-master binary provided in this PR and don't specify -E  PCM:8000:8000 VLC 3.0.1 on Ubuntu 16.04 LTS shows 0 buffers played. When specifying the option and running 
setconf -k h -v 100
setconf -k q -v 1

I can hear audio.

**Comment by fcastroruiz** [comment]
Update last firmware work for me to solved my audio problem

**Comment by nik0** [comment]
@fcastroruiz, what was your problems? What are the options your are using (S/W volume, H/W volume, filter)
@sanderdh, with setting the volume it is working fine? (as before)

**Comment by sanderdh** [comment]
With setting the audio options stated above and providing -E PCM:8000:8000 I can hear audio (it is not very loud and I get some interruptions). I online provided the 'h' option after a reboot and it worked.

**Comment by don86nl** [comment]
Hello, I want try to use the PCMU codec. But when I use the command
`v4l2rtspserver-master with -E PCM:8000:8000`
then it says 
> /system/sdcard/bin/v4l2rtspserver-master: invalid option --E
and then gives me the list of options available.
I am up to date with the recent files.

**Comment by nik0** [comment]
@don86nl,
This branch is not released yet. You need to get the binaries from it (v4l2rtspserver-master and setconf).
I need more feedback to release it.
thanks,

Nik0

**Comment by don86nl** [comment]
@Nik0 that would explain it, haha. Thanks.

**Comment by iashwinprasada** [comment]
can confirm OPUS is working for me

**Comment by nik0** [comment]
A new one will come soon using the SDK API ...

**Pull request closed without merging**
