### PR TITLE
Lighttpd

### PR DESCRIPTION
**Pull request by nik0**
Add module SSL for https (need new crypto libs in lib folder)
Add mod_accesslog

### CODE REVIEW

**Comment by jmtatsch** [comment]
Awesome! Thank you!

**Comment by jmtatsch** [comment]
Did you manage to configure ssl already?

**Comment by nik0** [comment]
Yes ! SSL is working (Chrome is not happy because the certificate is generated locally) but here is how I did it:
I follow this https://redmine.lighttpd.net/projects/1/wiki/HowToSimpleSSL
I get a openssl.cnf file here http://web.mit.edu/crypto/openssl.cnf
To generate the certificate:
```
export OPENSSL_CONF=./openssl.cnf
cd /system/sdcard/config/
openssl req -new -x509 -keyout lighttpd.pem -out lighttpd.pem -days 365 -nodes
chmod 400 lighttpd.pem
```
In the lighthttpd.conf:

`server.modules              = ("mod_auth", 
                               "mod_authn_file",
			       "mod_redirect",
                               "mod_rewrite",
                               "mod_cgi",
                               "mod_fastcgi",
			       "mod_dirlisting",
			       "mod_staticfile",
			       **"mod_openssl"**
				)
cgi.assign                 = ( 
                               ".cgi" => "/bin/sh" )

**$SERVER["socket"] == ":443" {
  ssl.engine = "enable" 
  ssl.pemfile = "/system/sdcard/config/lighttpd.pem" 
}**
`

et voila ... I guess I didn't forget any steps ...

**Comment by jmtatsch** [comment]
Works like a charm, thank you.

**Comment by mixpc** [comment]
Hello,

@nik0 Could we get SSL (both encryption and authentication) from an SSL service (3rd party) such as Certbot? To that end I would need to know what OS CFW is running on, but cannot get much info:

```
[root@DAFANG:~]# uname -a
Linux DAFANG 3.10.14 #21 PREEMPT Thu Oct 19 11:38:16 CST 2017 mips GNU/Linux

[root@DAFANG:~]# cat /etc/os-release
ISA_VERSION=5.5.1.243
```

Could you please advise? Thanks in advance!

**Comment by nik0** [comment]
Choose “other Linux” ?

**Comment by nik0** [comment]
it seems that the script need basename.
Anyway after looking at it it needs apt, python, ... things that we don't have.
maybe they have an online script, script for IOT devices ...

**Pull request merged**
