### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by Cabalist**
Hey there,

I finally got a couple of these cameras.  Great job on this new firmware.  They are incredibly useful now!  I went through the scripts and did some cleanup.  Mostly whitespace but a few refactors to reduce the load on the little embedded devices.  

The biggest change was double quoting a bunch of variables to make sure they can't be split.  As the web interface has no password at the moment it was possible to execute arbitrary code by say... changing the hostname to something like "derp; rm -rf /; ls.  

There are probably a good amount of security holes to fill but this was low hanging fruit.  :)

If the amount of whitespace churn is overwhelming you can append `?w=1` (i.e. `https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/172/files?w=1` ) to the end of url to ignore whitespace only changes.  :)  Let me know if you have any questions or if there is something broken that I missed!

### CODE REVIEW

**Comment by Cabalist** [comment]
Oh.  I did not touch `func.cgi` or `api.cgi` as they appeared to be other project's code.

**Comment by EliasKotlyar** [comment]
Hello @Cabalist,

Thanks for all the changes. Have you used any kind of tool to automatically clean up, or you did everything yourself?

Greatings
Elias

**Comment by Cabalist** [comment]
Shellcheck did most of it. :)  You can add CI for this project to make sure
fewer bugs are introduced (at least through the shell commands).

Thanks for all your work on this I am coming from Foscam land and these
cameras are like a breath of fresh air with software you’ve made.

**Comment by Cabalist** [comment]
@wojtulab Good catch!  My bad!

**Pull request merged**
