### PR TITLE
[SCRIPT] Merging script for config files

### PR DESCRIPTION
**Pull request by gysmo38**
I create a scritp to merge .conf.dist and .conf file.
The script will check if there is new variables on conf.dist file and added in the config file is it exist.

You can test it, if it is ok for everybody we can add this script at the end of the update process. It is to avoid breaking features when there is parameters missing in an old config file.

### CODE REVIEW

**Comment by saipsa** [comment]
It would be  better if instead of enumerating all files manually, you scan for all *.conf files and do the merging, so if a new file is added at a later date, it would still work.

**Comment by gysmo38** [comment]
That was my first thought but there is some conf file that have no parameters so it can not be updated.
(example hostname.conf, wpa_supplicant.conf). Or I can change it to create an exclude filter...

**Comment by jmtatsch** [comment]
Exclude filter would be great.

**Comment by gysmo38** [comment]
I will made the correction and made a new PR.

**Pull request closed without merging**
