### PR TITLE
Bulma 0 8 2

### PR DESCRIPTION
**Pull request by gysmo38**
New PR for Bulma version 0.8.2

### CODE REVIEW

**Comment by jmtatsch** [comment]
Sorry for closing. I had accumulated some mess i needed to clean out.

**Comment by gysmo38** [comment]
no problem :)

**Comment by jmtatsch** [comment]
If you are knowledgeable about bulma, maybe you know a way of solving https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/e27f4b3c62cc505a9ac17633ecc2c8e2a1d5ca4a/firmware_mod/www/index.html#L187 properly without the blank target? Otherwise currently the link is not resolved properly.

**Comment by gysmo38** [comment]
I am not fan of bulma... I learn it because this project use it. I will check if i can found something

**Pull request closed without merging**
