### PR TITLE
Remove device name from entity

### LINKED ISSUE #1870: Discovered MQTT entities with a name that is equal to the device name
### Description

After updating Home Assistant to version 2023.8.0 I've got the following warning.

Discovered MQTT entities with a name that is equal to the device name

This stops working in version 2024.2.0. Please address before upgrading.
Some MQTT entities have an entity name equal to the device name. This is not expected. The entity name is set to null as a work-a-round to avoid a duplicate name. Please inform the maintainer of the software application that supplies the affected entities to fix this issue.

List of affected entities:

switch.dafang_rtsp_server
switch.dafang_motion_send_telegram
switch.dafang_ir_led
switch.dafang_motion_send_emails
switch.dafang_motion_detection
switch.dafang_ir_filter
switch.dafang_auto_night_detection
switch.dafang_blue_led
switch.dafang_yellow_led
switch.dafang_recording
camera.dafang_motion_snapshot
sensor.dafang_light_sensor
switch.dafang_night_mode
binary_sensor.dafang_motion_sensor
cover.dafang_move_up_down
switch.dafang_motion_tracking
cover.dafang_move_left_right
switch.dafang_timelapse

according tho this link https://developers.home-assistant.io/blog/2023-057-21-change-naming-mqtt-entities/ they made some changes to the MTTQ entries naming.

Additional information:  https://community.home-assistant.io/t/psa-mqtt-name-changes-in-2023-8/598099

### PR DESCRIPTION
**Pull request by TheZoker**
Maybe fixes #1870

### CODE REVIEW

**Review by jmtatsch — COMMENTED** [review]
Please let us know if it really solves the issue 😉

**Comment by TheZoker** [comment]
After applying this change to my dafang cam and restarted HA, the error is gone and all the functions are still there. So for me this solves the issue 👍

**Comment by D0m3L** [comment]
Works for me. Thanks.

**Comment by wuzyzy** [comment]
Nice! Works for me too.

**Comment by TheZoker** [comment]
@jmtatsch I think this issue can be closed then?

**Comment by stshome2** [comment]
Thank you, Works for me. After some MQTT cleaning no message in HA anymore

**Comment by gerard33** [comment]
@stshome2 can you explain what MQTT cleaning you have done?
I still have the warnings in the HA log after installing the beta version.

image

**Comment by stshome2** [comment]
I used the Windows program MQTT-explorer to connect to Homeassistant. You see all the „old“ and „new“ camera entries.
You can delete the old ones. After that the log should be clean.
Hope it helps

**Comment by gerard33** [comment]
Thanks, I already used MQTT explorer but for me no old and new camera. But after switching the camera off and on the warnings are gone.

**Pull request merged**
