### PR TITLE
DropbearMulti (v2019.78) + corrected path

### PR DESCRIPTION
**Pull request by nik0**

### CODE REVIEW

**Comment by nik0** [comment]
@Yannik ,
And now ?

**Comment by Yannik** [comment]
the scp symlink is missing. also, i'd recommend to squash this into one commit.

**Comment by nik0** [comment]
Which link ?
The path is "/usr/bin:/bin:/system/bin:/system/sdcard/bin/"

**Comment by Yannik** [comment]
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/pull/1322/files#diff-548b98f98199a9ad72dbb6c8e38a16c4R212

**Comment by Yannik** [comment]
@nik0 the scp symlink is already in master. therefore i'd squash this into one commit and merge master into beta.

**Comment by nik0** [comment]
Squashed ....
Hopefully I didn't break something ...

**Comment by Yannik** [comment]
yeah, this looks good :) now you only need to fix the commit message.

**Comment by Yannik** [comment]
@nik0 Can you make the message a bit more self-explanatory? Like:

> Update dropbear PATH to include /system/bin and /system/sdcard/bin (related to #1322)

`New version of dropbear` does not really explain what has changed.

**Pull request closed without merging**
