### PR TITLE
Software night/day detection (to be tested before)

### PR DESCRIPTION
**Pull request by nik0**
Using ImageMagick with this trick: https://stackoverflow.com/questions/7935814/how-to-determine-if-image-is-dark-high-contrast-low-brightness

### CODE REVIEW

**Comment by aartrost** [comment]
Thanks for this! I'm in the process of testing, so far I get a `/system/sdcard/bin/convert: can't load library 'libMagickCore.so.5'` error when running `ldrSW.sh`. The file is present in the sdcard/libs folder but no dice.

**Comment by nik0** [comment]
Try: export LD_LIBRARY_PATH=/system/sdcard/lib:$LD_LIBRARY_PATH before starting the script

**Comment by aartrost** [comment]
This worked, however it now `can't load library 'libjpeg.so.62'`. Seems like this file is entirely missing

**Comment by nik0** [comment]
Oups, I will update it

**Comment by aartrost** [comment]
Great! I'll resume testing as soon as that's there

**Comment by nik0** [comment]
And now ?

**Comment by aartrost** [comment]
That fixed all issues and getting readings now. I'll be testing the sensitivity now in a dark room. I'll report back asap.

**Comment by nik0** [comment]
Great, thanks
I am sure the algorithm can be improved, I have problem when it is starting to get dark, the camera goes night on, night off all the time
I need to think about that

**Comment by aartrost** [comment]
Yes, there's definitely a feedback loop because the camera can't differentiate between a scene lit by daylight or IR light. @jthwho had some interesting comments regarding this here: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/332#issuecomment-398191221. Perhaps we can somehow read the camera's gain and use that to extrapolate a more realistic brightness reading.

**Comment by nik0** [comment]
What is the log of ldrSW.sh script ?

**Comment by aartrost** [comment]
> [root@cam-livingroom:scripts]# ./ldrSW.sh 
AVG=5 - DAYHIGHT= - DAYLOW=20 - NIGHTHIGH=30 - NIGHTLOW= - TIME=5
Status=ON AVGMEASUREMENT =59
Night mode ON, measure=59 lt than 30 => night mode off
Status=OFF AVGMEASUREMENT =55
Status=OFF AVGMEASUREMENT =47
Status=OFF AVGMEASUREMENT =38
Status=OFF AVGMEASUREMENT =40
Status=OFF AVGMEASUREMENT =37
Status=OFF AVGMEASUREMENT =36
Status=OFF AVGMEASUREMENT =39
Status=OFF AVGMEASUREMENT =46
Status=OFF AVGMEASUREMENT =46
Status=OFF AVGMEASUREMENT =46
Status=OFF AVGMEASUREMENT =46
Status=OFF AVGMEASUREMENT =46
Status=OFF AVGMEASUREMENT =46
Status=OFF AVGMEASUREMENT =46
Status=OFF AVGMEASUREMENT =46
Status=OFF AVGMEASUREMENT =46
^C
[root@cam-livingroom:scripts]# ./ldrSW.sh 
AVG=5 - DAYHIGHT= - DAYLOW=20 - NIGHTHIGH=30 - NIGHTLOW= - TIME=5
Status=OFF AVGMEASUREMENT =41
Status=OFF AVGMEASUREMENT =36
Status=OFF AVGMEASUREMENT =32
Status=OFF AVGMEASUREMENT =26
Status=OFF AVGMEASUREMENT =20
Status=OFF AVGMEASUREMENT =19
Night mode OFF, measure=19 lt than 20 => night mode on
Status=ON AVGMEASUREMENT =26
Status=ON AVGMEASUREMENT =32
Night mode ON, measure=32 lt than 30 => night mode off
Status=OFF AVGMEASUREMENT =31
Status=OFF AVGMEASUREMENT =31
Status=OFF AVGMEASUREMENT =31
Status=OFF AVGMEASUREMENT =22
Status=OFF AVGMEASUREMENT =15
Night mode OFF, measure=15 lt than 20 => night mode on
Status=ON AVGMEASUREMENT =24
Status=ON AVGMEASUREMENT =33
Night mode ON, measure=33 lt than 30 => night mode off
Status=OFF AVGMEASUREMENT =35
Status=OFF AVGMEASUREMENT =38
Status=OFF AVGMEASUREMENT =38
Status=OFF AVGMEASUREMENT =31
Status=OFF AVGMEASUREMENT =24
Status=OFF AVGMEASUREMENT =25
Status=OFF AVGMEASUREMENT =26
^C
[root@cam-livingroom:scripts]# ./ldrSW.sh 
AVG=5 - DAYHIGHT= - DAYLOW=20 - NIGHTHIGH=40 - NIGHTLOW= - TIME=2
Status=OFF AVGMEASUREMENT =26
Status=OFF AVGMEASUREMENT =27
Status=OFF AVGMEASUREMENT =27
Status=OFF AVGMEASUREMENT =28
Status=OFF AVGMEASUREMENT =28
Status=OFF AVGMEASUREMENT =28
Status=OFF AVGMEASUREMENT =28
Status=OFF AVGMEASUREMENT =28
Status=OFF AVGMEASUREMENT =28
Status=OFF AVGMEASUREMENT =29
Status=OFF AVGMEASUREMENT =30
^C
[root@cam-livingroom:scripts]# ./ldrSW.sh 
AVG=5 - DAYHIGHT= - DAYLOW=25 - NIGHTHIGH=40 - NIGHTLOW= - TIME=2
Status=OFF AVGMEASUREMENT =30
Status=OFF AVGMEASUREMENT =30
Status=OFF AVGMEASUREMENT =27
Status=OFF AVGMEASUREMENT =23
Night mode OFF, measure=23 lt than 25 => night mode on
Status=ON AVGMEASUREMENT =30
Status=ON AVGMEASUREMENT =32
Status=ON AVGMEASUREMENT =35
Status=ON AVGMEASUREMENT =41
Night mode ON, measure=41 lt than 40 => night mode off
Status=OFF AVGMEASUREMENT =40
Status=OFF AVGMEASUREMENT =29
Status=OFF AVGMEASUREMENT =23
Night mode OFF, measure=23 lt than 25 => night mode on
Status=ON AVGMEASUREMENT =30
Status=ON AVGMEASUREMENT =30
Status=ON AVGMEASUREMENT =37
Status=ON AVGMEASUREMENT =43
Night mode ON, measure=43 lt than 40 => night mode off
Status=OFF AVGMEASUREMENT =42
Status=OFF AVGMEASUREMENT =37
Status=OFF AVGMEASUREMENT =38
Status=OFF AVGMEASUREMENT =38
Status=OFF AVGMEASUREMENT =39
Status=OFF AVGMEASUREMENT =47
Status=OFF AVGMEASUREMENT =46
Status=OFF AVGMEASUREMENT =46

This is testing in a darkened room, pointing at different scenes. The last one is a good example of the feedback loop.

**Comment by aartrost** [comment]
So there seems to be a way to get the camera's gain here: https://github.com/Dafang-Hacks/Main/blob/5396ed5bc912672d08b6e40b38d820ac96ec830b/v4l2rtspserver-master/inc/imp/imp_isp.h#L868

However, I'm not well versed enough in C to actually extract that for use. Could you see if this value can be made available in the bash script? Perhaps we can then better compensate for the IR light.

**Comment by aartrost** [comment]
Hey @nik0 

Just curious why this got closed, do you think we won't have a chance to achieve proper night detection through this method? I'd be glad to help out if you intend to keep going at this problem.

**Comment by nik0** [comment]
I plan to work on this later. I need to experiment the API you mentioned, but I am not sure it will work. 
For me IMP_ISP_Tuning_GetBrightness will return the brightness you set with IMP_ISP_Tuning_SetBrightness. This is not dynamic

**Comment by aartrost** [comment]
I see, that is a bummer. Thanks for the update!

**Comment by puddly** [comment]
`IMP_ISP_Tuning_GetTotalGain` does obtain the sensor gain. Unfortunately, the maximum value of 7844 is hit pretty quickly as the scene gets darker.

The IR light looks to only be visible in the red and blue channels. If you use the HSL color space and compute the fraction of magenta-tinted pixels (e.g. with a hue between 125 and 180 degrees), you can get a rough measure of how much the IR LEDs are actually contributing to the brightness of the image (assuming you're not in a bright magenta room).

I wonder how many of these features need to be combined before they work as well as the $0.15 light sensor?

**Comment by puddly** [comment]
The only usable sensor attributes exposed by `libimp.so` look to be:

- `IMP_ISP_Tuning_GetWB_Statis`
	- `rgain` (red gain)
	- `bgain` (blue gain)

- `IMP_ISP_Tuning_GetEVAttr`:
	- `again` (analog gain)
	- `dgain` (digital gain)
	- `gain_log2` (not sure which gain this refers to)
	- `ev` (exposure value)
	- `ev_log2` (it doesn't seem to be `log2(ev)`)
	- `expr_us` (exposure time in microseconds)

- `IMP_ISP_Tuning_GetTotalGain`
	- `total_gain` (not sure how this relates to all the other gains)

`ev`, `rgain`, and `bgain` seem like the most promising attributes.

**Pull request closed without merging**
