### PR TITLE
Update flashinguboot.md

### PR DESCRIPTION
**Pull request by cf8geek**
added a disadvantage I didn't realize until it was too late

### CODE REVIEW

**Comment by jmtatsch** [comment]
I don't think this is true. If no uEnv.bootfromsdcard.txt is found, it should default to boot from NAND also for stock fw.

**Comment by cf8geek** [comment]
@jmtatsch I only know this because I inadvertently tested it. I could not get a demo.bin to load with the custom bootloader. If your testing yields different results, perhaps we have slightly different hardware?

**Comment by jmtatsch** [comment]
@EliasKotlyar can you chime in on this?

**Comment by jmtatsch** [comment]
Did you enable booting from NAND with an appropriate uEnv.txt in your sd root?
like mv uEnv.bootfromnand.txt uEnv.txt?

**Comment by cf8geek** [comment]
No, but how does this help? If the ONLY file on the microSD card is demo.bin, it doesn't really matter if there was previously a .txt file there, does it? Also, which NAND does "bootfromnand" boot from?

**Comment by jmtatsch** [comment]
Demo.bin is only flashed if there is nothing else on the sd card. Uboot boots from the nand address in uEnv.txt I think.

**Comment by cf8geek** [comment]
My point being you CAN'T flash demo.bin from the microSD card after performing the bootloader replacement (hence this pull request). Or at least I couldn't on my two cameras. Which makes sense, if the bootloader is looking for uEnv.txt instead of demo.bin.

**Comment by cf8geek** [comment]
Have you confirmed?

**Comment by prawnz** [comment]
> @jmtatsch I only know this because I inadvertently tested it. I could not get a demo.bin to load with the custom bootloader. If your testing yields different results, perhaps we have slightly different hardware?

I am having this at the moment.. My Wyze Cam Pan can't even manually install any other firmwares now

**Comment by cf8geek** [comment]
@prawnz Were you able to pull a working bootloader from another camera to remedy your problem? That's what I ended up doing.

**Comment by prawnz** [comment]
@cf8geek nope I don't have another camera on the side to be able to do that.. Are you able to share your bootloader?

**Pull request closed without merging**
