### PR TITLE
Add MQTT send mail alert switch

### PR DESCRIPTION
**Pull request by gysmo38**
I try to add MQTT send mail alert switch.
It work for me. 
I add it because I would like to use motion like motion tracker for the house all the time and have mail alert only when away.

### CODE REVIEW

**Comment by gysmo38** [comment]
You want another name?
It is a switch to activate or deactivate sending mail on motion detection.

**Comment by jmtatsch** [comment]
for on you listen on /motion/send_mail/set
for off you listen on /motion/detection_mail/set
should probably both be /motion/send_mail/set?

**Comment by gysmo38** [comment]
You are right :)  Thank you.

**Comment by jmtatsch** [comment]
Looks good to me

**Pull request merged**
