### PR TITLE
Add batman-adv mesh networking support

### PR DESCRIPTION
**Pull request by harisokanovic**
Add support for WiFi mesh networking via batman-adv kernel module. See commit log for details.

### CODE REVIEW

**Comment by jmtatsch** [comment]
Crazy stuff. How do you use that? A mesh of a hundred surveillance cameras down the whole street?

**Comment by harisokanovic** [comment]
Heh, nothing too crazy. I'm mostly interested in mesh to improve reliability of one camera that's pretty far from the DVR (access point). It sometimes drops out with interference. This allows it to use a closer camera as relay. Time will tell if it works...
It's also pretty cool that we can mesh a $26 camera! Commercial options in this space are fairly expensive by comparison.

**Comment by harisokanovic** [comment]
Bump

**Comment by cadavre** [comment]
If it's configurable and not enabled by default – no reason to not merge.

**Comment by jmtatsch** [comment]
The repo owner and the contributors with merge rights had sort of an understanding that we don't just merge executables which we did not code review and build ourselves for obvious security reasons. The benefits for most users are so little that it doesn't justify the above work for me. However, everyone can decide for themselves just to pull in these changes in their own forks and take some potential risk. That is why I leave this PR for everyone to see and tinker with it.

**Comment by harisokanovic** [comment]
@jmtatsch Have you guys considered openembedded, buildroot, or something similar? These build systems provide a way to fundamentally reproduce entire OS images from source code. They would enable safe/reviewable community contributions to any constituent code, whether it's in a driver or a boot script.

Otherwise, most people are limited to only scripting changes which arbitrarily limits improvements that can be made to this project.

**Comment by jmtatsch** [comment]
@harisokanovic As the name says This project is mostly just a hack :)There is a fork that does things right and it’s called openfang. Unfortunately development there has stalled a bit. Maybe you can contribute a bit there to reinvigorate the project a bit. I was planning on porting some stuff over as soon as the update routine works. Until then I’m here trying to keep everything together with minimal effort and merging some community improvements.

**Comment by harisokanovic** [comment]
Everything useful in the open source world starts off as "just a hack" :)
I'm really glad to see that someone took time to construct a proper build system for this project. I'll take a look when I have some free time.

**Pull request closed without merging**
