### PR TITLE
added mosquitto_pub & sub  

### LINKED ISSUE #35: installing packages on the camera
Hi Elias,

I would like to install packages on the camera, how might one go about doing this?
I want to install probably mosquitto (and maybe python) to control the LEDs via MQTT and send a few other states to my home automation software (home-assistant), I'm also thinking of potentially installing motion to handle motion detection.
I know where to get the software but I'm not sure where to start from and where to install the files to.

Thanks

### PR DESCRIPTION
**Pull request by shinebar1001**
Fixes #35

### CODE REVIEW

**Comment by shinebar1001** [comment]
Fixes #88 as well, f*cked up some files with notepad++ on windows.

**Comment by lolouk44** [comment]
hi @shinebar1001 
How do you use mosquitto?
I tried with this command:
```
/system/sdcard/bin/busybox nohup /system/sdcard/bin/mosquitto_pub -h 'host_address' -p 16306 -u 'username' -P 'password' -t 'Garage/LED_Strip' -m ' {"state":"ON","color":{"r":255,"g":255,"b":255}}'
```
yet I get `Error: Connection refused`
If I try the same command directly on Ubuntu (without the `/system/sdcard/bin/busybox nohup /system/sdcard/bin/`) it works.

Any idea?

**Comment by shinebar1001** [comment]
Do you try this in a script executed from the webserver? It works on the command line:

`[root@Pucki-Cam:tmp]# /system/sdcard/bin/busybox nohup /system/sdcard/bin/mosquitto_pub -h '192.168.190.1' -p 1883 -u 'user' -P 'pass' -t 'Garage/LED_Strip' -m ' {"state":"ON","color":{"r"
:255,"g":255,"b":255}}'
nohup: appending output to nohup.out
[root@Pucki-Cam:tmp]#`

works: 
image

I had some problems to invoke mosquitto_pub from the webserver, becaus mosquitto_pub is a wrapper, as the library is not in the LD-Path - so probably try this:

export LD_LIBRARY_PATH='/thirdlib:/system/lib:/system/sdcard/lib'
/system/sdcard/bin/busybox nohup /system/sdcard/bin/mosquitto_sub.bin -h $HOST -u $USER -P $PASS -t ${TOPIC}set ${MOSQUITTOOPTS} > $FIFO 2> /dev/null &

**Comment by lolouk44** [comment]
Thanks but it definitely doesn't work for me.
I'll try and set a simple mosquitto_sub on one of my servers in case there's an issue with cloudmqtt

**Comment by shinebar1001** [comment]
That's interesting.  I signed up for a cloudmqtt-account and it works here:

[root@Pucki-Cam:~]# /system/sdcard/bin/mosquitto_pub -h 'm23.cloudmqtt.com' -p 1
6909 -u 'user' -P 'pass' -t 'Garage/LED_Strip' -m ' {"state":"ON","c
olor":{"r" :255,"g":255,"b":255}}'
[root@Pucki-Cam:~]# echo $?
0

as the error is "connection refused" - you didn't forget to change a firewall?

**Comment by lolouk44** [comment]
something's not right: I just did a simple sub -t 'test' on a raspberry pi (right) and try to submit a simple message on the dafang (left) and get the connection refused error...
image

**Comment by lolouk44** [comment]
Actually trying to stay on the dafang to take it even a step back. Just typing /system/sdcard/bin/mosquitto_sub -t 'test' fails with connection refused...
what am I doing wrong?

**Comment by shinebar1001** [comment]
there is no default config for mosquitto_sub on the dafang, so you have to specify host + port + user + pass, as these are not filled.
Can you please  try
/system/sdcard/bin/mosquitto_pub -h 192.168.0.21 -p 1883 -t 'test' -m 'test message' -d
this requires the mosquitto-server on port 1883 without authentification.

I just installed mosquitto on a raspberry pi:
```

[root@Pucki-Cam:~]# /system/sdcard/bin/mosquitto_pub -h 192.168.180.33 -p 1883 -t 'test' -m 'test message' -d
Client mosqpub|17975-Pucki-Cam sending CONNECT
Client mosqpub|17975-Pucki-Cam received CONNACK
Client mosqpub|17975-Pucki-Cam sending PUBLISH (d0, q0, r0, m1, 'test', ... (12 bytes))
Client mosqpub|17975-Pucki-Cam sending DISCONNECT
```

**Comment by lolouk44** [comment]
Missed the firewall bit. On the basis that it works from a non Dafang device, I doubt firewall would be an issue. I've tried to flash a new card in case something was wrong with the data on it but still facing the same issue...
when adding -d to the command, I get nothing else but `Error: Connection refused`
I tried adding host, port, user and password to mosquitto_sub but again get the same connection refused message. Is there a built in firewall on the dafang that I'm not aware of and need to open a port?

**Comment by lolouk44** [comment]
Please ignore any of this. Back in the beginning I had blocked the dafang from connecting to the internet on my router to test whether the mihome app could still "spy" on me and never removed the restrictions. 
Now it all works. Doh !
Sorry for being a pain and thanks for your patience

**Comment by shinebar1001** [comment]
:)
No worry! I'll try to compile a busybox with telnet these days to make debugging of such situations easier.

**Comment by EliasKotlyar** [comment]
Hello @shinebar1001 ,

Actually, the busybox binary already include telnet:

[root@DAFANGHACKS:bin]# ./busybox telnet
BusyBox v1.22.1 (2017-12-06 17:58:13 CET) multi-call binary.

Usage: telnet [-a] [-l USER] HOST [PORT]

Connect to telnet server

	-a	Automatic login with $USER variable
	-l USER	Automatic login as USER

**Comment by shinebar1001** [comment]
Okay, thank you... I used the original busybox in /bin :) doh!!! didn't realize that this one was in PATH...
But anyway, I learned a lot... And now I'll simplify the mqtt-status a Little bit :P

**Pull request merged**
