### PR TITLE
Fix grep_text for correct output from bin/motor

### LINKED ISSUE #656: motor_PTZ only goes right and up
Not sure what im doing wrong but the parameters to motor_PTZ seem to increment :)
Ex:
cmd=motor_PTZ&x_axis=100&y_axis=100
Will move 100 on each axes...

### PR DESCRIPTION
**Pull request by nathanchantrell**
Output from bin/motor has changed, updated to reflect this. Fixes #656

### CODE REVIEW

**Comment by nik0** [comment]
Thanks catching this ...

**Comment by pixeldublu** [comment]
That was fast :) 

Thumbs up!

**Comment by pixeldublu** [comment]
Still not ok... now its inverted... always goes left :)

**Comment by pixeldublu** [comment]
Maybe string lower of $1 and compare it a gains "x"

**Comment by nathanchantrell** [comment]
Oh that's odd. It's working correctly for me with just that change and I can't see anything else that would cause that.

If you log in via SSH and run /system/sdcard/bin/motor -d s
do the x and y values it returns increment and decrement as you move the camera?

**Comment by pixeldublu** [comment]
Will test tonight when i get home.

I know that motor_left motor_right works correctly.

**Comment by pixeldublu** [comment]
I think its ok now. Thanks alot!!

**Pull request merged**
