### PR TITLE
Dropbear new bin with /system/bin as path

### PR DESCRIPTION
**Pull request by nik0**

### CODE REVIEW

**Comment by Yannik** [comment]
This includes a commit regarding lighttpd, which should not be part of this PR. Also the PR is missing the symlink `/system/bin/scp` to dropbearmulti

**Comment by nik0** [comment]
I made again a git mistake 🙄
Will redo PR

**Comment by jmtatsch** [comment]
Symlink is already on master 😉

**Comment by Yannik** [comment]
in that case, you should merge master into beta.

**Pull request closed without merging**
