### PR TITLE
Motion configuration

### PR DESCRIPTION
**Pull request by nik0**
Web configuration for https://github.com/EliasKotlyar/Xiaomi-Dafang-Software/pull/8

### CODE REVIEW

**Comment by iashwinprasada** [comment]
There is an error in the html config page, hence not able to set positions 

image

**Comment by nik0** [comment]
Do you have cgi-bin/getMotionInfo.cgi installed ?

**Comment by iashwinprasada** [comment]
yes. also have you added the new setconf binary to the pull request?

**Comment by nik0** [comment]
I modified a bit the getMotionInfo.cgi to add some robustness
Yes you also need the new setconf
can you ssh on the Camera and execute  /system/sdcard/www/cgi-bin/getMotionInfo.cgi
and give me the result

**Comment by jmtatsch** [comment]
@nik0 wouldn't it need your new rtspserver binary?

**Comment by nik0** [comment]
Yes ! The pull request https://github.com/EliasKotlyar/Xiaomi-Dafang-Software/pull/8 should be merged and compiled first ....

**Comment by jmtatsch** [comment]
@ Ah ok, why don't you add your compiled binaries in this pr here? Then everything needed for this increment would be together in one place.

**Comment by nik0** [comment]
I didn’t want to add a binary from a unmerged branch...

**Comment by nik0** [comment]
... and I am not sure that the compilation script are the same from master and my branch. I modified some scripts

**Comment by nik0** [comment]
I will add the binaries later in the day ...

**Pull request merged**
