### PR TITLE
letsencrypt: support dns validation

### PR DESCRIPTION
**Pull request by Yannik**

### CODE REVIEW

**Comment by jmtatsch** [comment]
Thank you for your contribution.

**Comment by Yannik** [comment]
@jmtatsch the [force-push](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/compare/c2d6c41733bdc5dc8764e74bf0c96efa9ed9ee20..be2cb151c0506f2a90a8d301627d5c5affc116c0) of @nik0 reverted this commit. why?

**Comment by Yannik** [comment]
image

**Comment by jmtatsch** [comment]
Just a GitHub rookie mistake, not on purpose.

**Comment by jmtatsch** [comment]
Any idea how I can pull this in again properly? Or could you just redo this pull request?

**Comment by nik0** [comment]
> @jmtatsch the [force-push](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/compare/c2d6c41733bdc5dc8764e74bf0c96efa9ed9ee20..be2cb151c0506f2a90a8d301627d5c5affc116c0) of @nik0 removed this commit. why?

My bad @Yannik 
Sorry about that
My git skills are very low ...

**Comment by Yannik** [comment]
@jmtatsch @nik0 I would strongly recommend disabling force-push for this repo, because force-pushing breaks the git tree for other people.

**Pull request merged**
