### PR TITLE
Build cfw-1.2.bin for Wyze cameras using latest firmware 4.9.4.28

### PR DESCRIPTION
**Pull request by mbevand**
rcfile.sh: better comments
Enable Wyze SD card with GPIO43
rcfile.sh: properly unmounts /system/sdcard
add official Wyze 4.9.4.28 firmware binaries
build cfw-1.2.bin with all these changes

### CODE REVIEW

**Comment by saipsa** [comment]
binaries built only by collaborators are accepted due to security concerns.

**Comment by mbevand** [comment]
Understandable. Do I recreate a pull request that excludes the last commit (d8f5f2b6f81c481fbff872b38cbc6c7f67a06881)?

**Comment by hamid-elaosta** [comment]
This also works with the latest 4.3.4.37 (I'm running it now).

**Comment by raulvasquez** [comment]
Is it possible to flash this cfw-1.2.bin using dd instead of the sdcard trick?

**Pull request merged**
