### PR TITLE
Enable support USB Ethernet

### PR DESCRIPTION
**Pull request by hcgonzalezpr**
Enable initial support USB Ethernet starting with the asix.ko driver.

This is my attempt to implement #236

### CODE REVIEW

**Comment by jmtatsch** [comment]
Thank you very much. For security reasons we should not check in compiled code.
Would you be so kind to contribute your compile_ethernet_driver.sh recipe to https://github.com/Dafang-Hacks/Main ?

**Comment by hcgonzalezpr** [comment]
@jmtatsch 
I don't know how to do that, I you can give me an example, im willing to give it a try.

But all I did was compile  https://github.com/Dafang-Hacks/kernel with the following entries as modules:
CONFIG_USB_USBNET=m
CONFIG_USB_NET_AX8817X=m

**Comment by ulflun88** [comment]
Nice feature to have!

**Comment by EliasKotlyar** [comment]
Many thanks. I checked the sources, it can be enabled trough the described kernel configurations. I enabled them by default in the kernel repository. So if someone is not trusting this modules, he can compile them by himself.

**Pull request merged**
