### PR TITLE
Creating a branch based on Beta for T20L

### PR DESCRIPTION
**Pull request by maxencep02**
Hi,
I am using a XiaoFang T20L and it is working stable for some time.
However, following issue :
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1128
The drivers have never been added/modified because it is impossible to know it is a T20L by script. 

Since you are using branches, I was thinking it could be possible to create a branch based on beta (or 2, based on master and beta), dedicated to T20L.
The changes are not huge, but they would help new starters and ease the update process (otherwise it is necessairy to exclude *.ko from the autoupdate filter.

With such branches, it is to the users to selects the T20L branches.

Maxence

### CODE REVIEW

**Comment by albertopinguino** [comment]
Hi! I'll try it asap and tell you if it works for me... Thank yoou in advance!

**Comment by jmtatsch** [comment]
I would activate the ZRAM only by default.
The guy that introduced the config option reversed a newer xiaofang and thats how they do it in the original fw.
If that runs stable for you no reason for potentially writing though your sdcards.

**Comment by maxencep02** [comment]
I am not very good at github. But I am not sure you can merge into beta since the drivers are not the same as t20. It might create a conflict no?

**Comment by jmtatsch** [comment]
Will undo as soon as I get home.

**Comment by maxencep02** [comment]
Is it possible to PR a complete branch? As I said it is my first PRs

**Comment by jmtatsch** [comment]
Apparently not if you dont have push rights. Let me clean up master & beta. The i will create a new t20l branch for you.

**Comment by albertopinguino** [comment]
> Apparently not if you dont have push rights. Let me clean up master & beta. The i will create a new t20l branch for you.

Hi! Any news for the branch? Thank you in advance...

**Pull request merged**
