### PR TITLE
Update create_hacked_firmware_dafang.sh

### PR DESCRIPTION
**Pull request by cactushydrocodone**
Updated the script to use the newest firmware available at the moment.

### CODE REVIEW

**Comment by jmtatsch** [comment]
Did you try the resulting cfw?

**Comment by RaymondSchnyder** [comment]
I did not, i only updated the script.
The building of the firmware works as the script says, but im unsure if i should flash it, as im not aware of a "not physical way" to test if before i flash it on the real hardware.
Are the some checks i can do in the firmware itself on pc  to be sure that the firmware is "valid"?

**Comment by jmtatsch** [comment]
Hmm, I guess we need someone adventurous then.
Do we know what is new in 5.5.1.327? Did you diff the firmware against the last one?
@EliasKotlyar could you run some sanity checks?

**Comment by RaymondSchnyder** [comment]
I could test it this evening on my hardware, after i made a sanity check.
I did not make a diff. Can i mount the blobs and diff the content?

**Comment by jmtatsch** [comment]
Possibly. Also you can hash the blobs and see if they changed.

**Comment by Acrilia** [comment]
I make the new update from mi-home to 5.5.1.327. I put the microsd with updated hack files, and now I ma in "read only mod" I can't modify anything when I'm in the http: menu of the dafang. Careful.

**Comment by jmtatsch** [comment]
Try to chkdsk your sdcard.

**Comment by Acrilia** [comment]
Thx, but nothing corrupted inside, I'll try with another after work to check, but It's since the update in 327 I can't change any option.

**Comment by RaymondSchnyder** [comment]
@Acrilia just to clarify: How did you update? Did you update with the mihome app or with the firmware on this github repo? If first, it sounds like your sdcard broke (Physically). This happens alot with sdcards. Try another sdcard if you have one and see if it works then. I hope it wasnt my firmware files that led to your issue.... :(

**Comment by RaymondSchnyder** [comment]
@jmtatsch i tested the firmware. I flashed it and it seems to work, but not with the hack.
If i insert the SD Card with the hack, the camera wont boot. Without SD Card, everything is fine.

**Comment by RaymondSchnyder** [comment]
@jmtatsch right now im debugging.  The firmware boots with the custom firmware, but it seems there is a syntax error in the run file.

image

**Comment by RaymondSchnyder** [comment]
Omg i see the problem... im such a dumbass.
I wanted to get all the updates and merged my repo with this, and git placed some comments in the files.... now the files are messed up

image
 i think thats the problem

**Comment by jmtatsch** [comment]
That is good news then that it works. Did you notice any improvements?

**Comment by RaymondSchnyder** [comment]
@jmtatsch the night mode switch works. I can switch to night mode (the violett mode) with a button press.
the grey mode is a bit buggy and seems not to work sometimes.
but all features seem to work as usual... the camera is running in my bedroom for days now and it still works!

**Comment by DreyVim** [comment]
Is it possible to lay out the original firmware 5.5.1.200, 5.5.1.243, 5.5.1.327 in assembled form (one demo.bin file) to restore the camera to the repository? Or tell me how to build them from the sources. Thank you.

**Comment by jmtatsch** [comment]
@DreyVim Interesting question, please open a separate issue for that.

**Comment by belch85** [comment]
I notice 5.5.1.327 discussion here, sorry to hi-jack, just purchased first DaFang on this firmware and [having no success](https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/545#issuecomment-402902185) installing the microSD bootloader.
Any chance you guys could take a look?
It appears (thought I've never successfully done one) that the camera just ignores the demo.bin file and boots up as per normal.  Any clues?

**Pull request merged**
