### PR TITLE
Script execution

### PR DESCRIPTION
**Pull request by nik0**
- Change the way the scripts (detection*) are launched
- Changed the motiontracking script as the tool changed

### CODE REVIEW

**Comment by Dopeyr** [comment]
Sorry to trouble you @nik0 but I don't think this commit does contain the system() changes. I'm seeing the same issue with the hanging, but also I see this is in the log:

```
2018-06-15 13:23:50.811 (9803.023s) [ivsMoveDetection]         ImpEncoder.cpp:774      0| Detect !!
2018-06-15 13:23:52.812 (9805.023s) [ivsMoveDetection]         ImpEncoder.cpp:570      0| Will execute command /system/sdcard/scripts/detectionOff.sh
Running: /system/sdcard/config/userscripts/motiondetection/x.sh off
motion off
2018-06-15 13:23:54.848 (9807.060s) [ivsMoveDetection]         ImpEncoder.cpp:570      0| Will execute command /system/sdcard/scripts/detectionOn.sh
Running: /system/sdcard/config/userscripts/motiondetection/x.sh on
motion on
2018-06-15 13:23:54.890 (9807.101s) [ivsMoveDetection]         ImpEncoder.cpp:774      0| Detect !!
2018-06-15 13:23:56.890 (9809.102s) [ivsMoveDetection]         ImpEncoder.cpp:570      0| Will execute command /system/sdcard/scripts/detectionOff.sh
Running: /system/sdcard/config/userscripts/motiondetection/x.sh off
motion off
2018-06-15 13:23:58.928 (9811.139s) [ivsMoveDetection]         ImpEncoder.cpp:570      0| Will execute command /system/sdcard/scripts/detectionOn.sh
Running: /system/sdcard/config/userscripts/motiondetection/x.sh on
motion on
```

i.e. I don't see any on of the output `LOG_S(INFO) << "Execute " << command << " returned:" << retVal;` should produce.

It's probably down to that 'missing' commit yesterday, it might not have been in the source when you built the binary?

**Comment by nik0** [comment]
You are right
git kill me ! I don't even see my yesterday commit about this ... It is not in master anymore ...

**Comment by nik0** [comment]
SHould be OK now

**Comment by Dopeyr** [comment]
Hehe, git can be a pain, especially when merging things around :) Seems to be fine now, I see the `Execute /system/sdcard/scripts/detectionOff.sh returned:0` in the log. I'll keep an eye on hanging/`ps` but I'm sure it's fine now.

**Pull request merged**
