### PR TITLE
Add directory to group daily stills/videos + mqtt-control upgrades

### PR DESCRIPTION
**Pull request by cadavre**
*This is an all-in-one PR. Please merge previous PRs or just this one if all is ok.*
*Can also cherry-pick `8ece525`.*

All files now are saved into single directory. This PR adds grouping in directories named by date.

### CODE REVIEW

**Comment by jmtatsch** [comment]
Can you rebase your PR on the current master and remove the binary please?

**Comment by cadavre** [comment]
Done. Binary and `.bin` are removed. How differently you want to add this binary? I can see that another binaries were added by commit as well.

**Comment by jmtatsch** [comment]
Thanks a million for all these improvements. I will add the binaries after the lunch break.

**Comment by jmtatsch** [comment]
The group directories do not seem to get created properly, can you look into it?

```
cp: can't create '/system/sdcard/DCIM/motion/videos/17-10-2019/17-10-2019_11.45.27.mp4': No such file or directory
cp: can't create '/system/sdcard/DCIM/motion/stills/17-10-2019/17-10-2019_11.45.27.jpg': No such file or directory
avconv version v13_dev0-1541-ge368b0cbf, Copyright (c) 2000-2018 the Libav developers
  built on May 17 2018 20:39:55 with gcc 4.7.2 (Ingenic r2.3.3 2016.12)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1bdf020] invalid size 8 in stsd
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1bdf020] error reading header: -1052488119
/tmp/video-Xlj5URY: Invalid data found when processing input
rm: can't remove '/tmp/video-Xlj5URY-lo.mp4': No such file or directory
```
Maybe something was lost in the merge.

**Comment by cadavre** [comment]
You're right. #1198 for fix.

**Comment by cadavre** [comment]
PS I don't use `telegram`, but I don't quite get this:
```
/system/sdcard/bin/avconv -i "$video_tempfile"  "$video_tempfile-lo.mp4"
```

I believe this is where:
```
avconv version v13_dev0-1541-ge368b0cbf, Copyright (c) 2000-2018 the Libav developers
  built on May 17 2018 20:39:55 with gcc 4.7.2 (Ingenic r2.3.3 2016.12)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1bdf020] invalid size 8 in stsd
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x1bdf020] error reading header: -1052488119
/tmp/video-Xlj5URY: Invalid data found when processing input
rm: can't remove '/tmp/video-Xlj5URY-lo.mp4': No such file or directory
```
...happens. I haven't changed a line there.

---

Can't we just change:
```
		debug_msg "Send telegram video"
		/system/sdcard/bin/avconv -i "$video_tempfile" "$video_tempfile-lo.mp4"
		/system/sdcard/bin/telegram v "$video_tempfile-lo.mp4"
		rm "$video_tempfile-lo.mp4"
```
to:
```
		debug_msg "Send telegram video"
		/system/sdcard/bin/telegram v "$video_tempfile"
```
?

**Comment by jmtatsch** [comment]
avconv was needed there because the mp4 file produced before was so broken (mainly the timecode) it would not play in telegram.
Hopefully the one produced by openRTSP is better and doesn't need this, I will give it a try.

**Comment by jmtatsch** [comment]
Turns out that recoding the video with avconf is no longer needed.
However video quality with openRTSP seems worse than the old method :( 
Lots of compression artefacts.
I will play around with the bitrates a bit.

**Comment by cadavre** [comment]
Had the same, but ended up with CBR 2000kbps in 720p on Dafang and no glitches. I believe this depends on camera model.

**Pull request merged**
