### PR TITLE
latest v4l2rtsp build

### PR DESCRIPTION
**Pull request by aartrost**
This fixes the admin panel video settings UI and allows for VBR/CBR video formats & bitrate to be set.

### CODE REVIEW

**Comment by saipsa** [comment]
Thank you for the PR.

I am not well versed with what best practices are w.r.t. PRs. But I think the binaries  built by the  trusted members should be merged.

I am not questioning your motives or anything @aartrost , just what I thought would be better from security point of view.

Please feel free to correct me if I am wrong. I am noob-ish.

Thanks.

**Comment by aartrost** [comment]
Yep, I 100% agree, as mentioned in my first post in https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/459. Feel free to ignore this PR in favor of a build from a core member.

**Comment by nik0** [comment]
@aartrost 
I will close it as I push another version
tell me if you are happy with it (same as your version)

**Comment by aartrost** [comment]
@nik0 Hey, sorry, just got around testing the new changes. All seems well with your version. Thanks!

**Pull request closed without merging**
