### PR TITLE
New binaires (latest internet sources)

### PR DESCRIPTION
**Pull request by nik0**
bftpd
	busybox
	fatlabel
	fsck.fat
	lighttpd
	mkfs.fat
	mosquitto
	openssl

### CODE REVIEW

**Comment by jmtatsch** [comment]
Are these binaries somewhat tested to work with our current functionalities?

**Comment by nik0** [comment]
Yes,
I will add them to the beta branch now. I am just wondering how to do if I want to publish them separately (to be tested one by one)

**Comment by jmtatsch** [comment]
I think all at once on the beta branch should be fine.

**Comment by Yannik** [comment]
@nik0 Which sources are used for these binaries exactly?

**Comment by nik0** [comment]
See the source tree here: https://github.com/Dafang-Hacks/Main 
in "Modules" folder

**Comment by tachang** [comment]
@nik0 Is avconv one of those sources?

**Comment by nik0** [comment]
> @nik0 Is avconv one of those sources?

No sorry, I did not recompile avconv. Do you need a newer version ?

**Pull request closed without merging**
