### PR TITLE
fix scp by adding /system/bin to dropbear PATH

### PR DESCRIPTION
**Pull request by Yannik**

### CODE REVIEW

**Comment by jmtatsch** [comment]
Hi Yannik,

sorry we cannot merge your PR because we decided not to check in binaries built by non-collaborators for security reasons.
Can you please check in a recipe for building dropbearmulti at https://github.com/Dafang-Hacks/Main? Then I will build it and check it in...

**Comment by Yannik** [comment]
Hi,

thank you for your reply. I appreciate it.

I first tried to build dropbear (2018) based on the sources in https://github.com/Dafang-Hacks/dropbear.
Unfortunately, this repo is not in buildable state. 
You can try building it using https://github.com/Dafang-Hacks/dropbear/blob/master/compile.sh. For example, neither the `configure` file nor the makefile used in the script do exist.

I suspect this repo was intended to replace the dropbear (dropbear-2017.75) sources in https://github.com/EliasKotlyar/Xiaomi-Dafang-Software, but never completed.

This was confirmed by checking the binary shipped in `firmware_mod`:
```
[root@xiaofang:~]# dropbearmulti dropbear -V
Dropbear v2017.75
```
This is the version of dropbear in the old repository.

Therefore, the modifications I've done apply to that repository.
I've consequently opened a PR with my changes here: https://github.com/EliasKotlyar/Xiaomi-Dafang-Software/pull/35

I can totally understand your reasons of not accepting binaries, I just hope you can still get this incorporated :-)

**Comment by jmtatsch** [comment]
The new dropbear added by nik0 compiles.
I applied your patch to the build script but am unable to login via ssh with the new executable.
@Yannik Can you have a look at it again?
@nik0 I just compiled with the compile_modules.sh and took the executable from  _install/bin . Did I miss something?

**Comment by nik0** [comment]
No, this is correct. I have the same issue that’s why I didn’t deliver it. I need to do more investigation

**Comment by jmtatsch** [comment]
But your executable from the beta branch runs just fine. The one with the extended path just rejects the connection after some encryption algo negotiations. Specifically after 
expecting a SSH2_MSG_KEX_ECDH_REPLY.

**Comment by nik0** [comment]
Yes I saw the same things. I thought it was because I am connecting to my camera from a Docker on Windows. 
How do you ssh on your device ?
I need to check, may be there is a missing configuration, or a compilation option ...

**Comment by jmtatsch** [comment]
I ssh -vvv root@192.168.181.41 and public key auth.

**Comment by nik0** [comment]
what is your host OS ?

**Comment by jmtatsch** [comment]
OSX 10.15.3. I might actually be a MTU size problem.

**Comment by nik0** [comment]
I investigated in this way, but I thought about the host MTU .
But it may the MTU off the camera ...

**Comment by Yannik** [comment]
My build is working just fine. The only change I made is [this](https://github.com/EliasKotlyar/Xiaomi-Dafang-Software/commit/1cfed9e1735c3bd376f86195318a9067161cb3d3).

Did you try if you have the same problem with my binary?

**Comment by jmtatsch** [comment]
Don’t have the old build env any more and would have preferred building the newer sources...

**Comment by Yannik** [comment]
Quoting my earlier reply:

> 
> I first tried to build dropbear (2018) based on the sources in https://github.com/Dafang-Hacks/dropbear.
> Unfortunately, this repo is not in buildable state. 
> You can try building it using https://github.com/Dafang-Hacks/dropbear/blob/master/compile.sh. For example, neither the `configure` file nor the makefile used in the script do exist.
> 
> I suspect this repo was intended to replace the dropbear (dropbear-2017.75) sources in https://github.com/EliasKotlyar/Xiaomi-Dafang-Software, but never completed.
> 
> This was confirmed by checking the binary shipped in `firmware_mod`:
> ```
> [root@xiaofang:~]# dropbearmulti dropbear -V
> Dropbear v2017.75
> ```
> This is the version of dropbear in the old repository.
>

**Comment by jmtatsch** [comment]
Well the newly added current sources by nik0 build just fine. The executable runs, it just dies somewhere during the cipher negotation process.

**Comment by jmtatsch** [comment]
MTU is 1500 on both systems. Also cannot connect from my 19 Ubuntu system.
I wish we could see the server side log. There is something at  /var/log/dropbear-e5dedfce/auth-9046c042-7 but it has zero bytes.

**Comment by Yannik** [comment]
> Well the newly added current sources by nik0 build just fine. The executable runs, it just dies somewhere during the cipher negotation process.

By newer sources I mean this: https://github.com/Dafang-Hacks/dropbear
I don't see any commits by nik0 there.

**Comment by nik0** [comment]
> > Well the newly added current sources by nik0 build just fine. The executable runs, it just dies somewhere during the cipher negotation process.
> 
> By newer sources I mean this: https://github.com/Dafang-Hacks/dropbear
> I don't see any commits by nik0 there.

I committed here:
https://github.com/Dafang-Hacks/Main/tree/master/Modules/dropbear

**Comment by nik0** [comment]
> MTU is 1500 on both systems. Also cannot connect from my 19 Ubuntu system.
> I wish we could see the server side log. There is something at /var/log/dropbear-e5dedfce/auth-9046c042-7 but it has zero bytes.

It seems that it "only" need to create folder /etc/dropbear/

**Comment by Yannik** [comment]
Look at https://github.com/EliasKotlyar/Xiaomi-Dafang-Software/blob/master/dropbear-2017.75/options.h. There's various options that are configured specifically for this project, for example `DSS_PRIV_FILENAME`.

**Comment by Yannik** [comment]
I recommend that you review all the changes that were applied to `options.h` of the old dropbear build: https://github.com/EliasKotlyar/Xiaomi-Dafang-Software/commits/master/dropbear-2017.75/options.h

**Comment by nik0** [comment]
Yeah you are right
Will do tomorrow 
Cheers

**Comment by jmtatsch** [comment]
Dropbear SSH multi-purpose v2019.78 now working beautyfully, only the scp not working because the scp: not found on the cam although link is /system/bin/scp.

**Comment by Yannik** [comment]
@jmtatsch 
I checked the binary (unfortunately there are no sources for this in the repo). @nik0 set `/usr/bin:/bin:/system/sdcard/bin/` as PATH but forgot `/system/bin`. That's why scp is not working.

**Comment by jmtatsch** [comment]
Just out of curiosity, how did you check for that in the binary? Did you look at the strings contained in the binary?

Would it be okay to just create the scp symlink in /system/sdcard/bin ?

**Comment by Yannik** [comment]
@jmtatsch `strings dropbearmulti |grep '/usr/bin'`. If you manage to create a symlink on a FAT filesystem, definitely ;-)

**Comment by nik0** [comment]
> @jmtatsch
> I checked the binary (unfortunately there are no sources for this in the repo). @nik0 set `/usr/bin:/bin:/system/sdcard/bin/` as PATH but forgot `/system/bin`. That's why scp is not working.

OK i will add it.
I didn't see it. I pushed the new source just now. Will do a new PR

**Comment by Yannik** [comment]
@nik0 I looked at your `localoptions.h` file. You shouldn't copy everything from `options.h` over, but just the options you are modifying :)

**Comment by nik0** [comment]
@Yannik 
Done !

**Comment by jmtatsch** [comment]
Everything is on the beta branch now and confirmed working so I will close this PR now. Thanks @nik0 and @Yannik

**Pull request closed without merging**
