### PR TITLE
added a mqtt-status + jq

### PR DESCRIPTION
**Pull request by shinebar1001**

### CODE REVIEW

**Comment by pplucky** [comment]
One question on mqtt status: will a request to the camera needs to be sent, for it to publish its status, or will the camera send it on itself periodically? Second option would be preferable, if possible.

**Comment by shinebar1001** [comment]
At the moment you need to send status_text to the camera and you'll get that reply. A periodical status is no problem and already on my personal roadmap.
Which interval would you suggest? More like every 5 minutes or more like once a minute?

**Comment by pplucky** [comment]
What I'd would be to define a parameter in the mqtt config file and do it based on the value assigned to it. Maybe define a minimum of 30sec under which it will not go, regardless of the config and allow anything above as per user setting.

**Comment by lolouk44** [comment]
I would second @pplucky let people choose but make it so that no less than 30 sec

**Comment by shinebar1001** [comment]
hey guys, the feature is added in e981159eade2b0e27ab420b498d5f37062daab5c - you'll need to update your mqtt-config, please see /system/sdcard/config/mqtt.dist and copy the last two Parameters.

**Pull request merged**
