### PR TITLE
Audio and framerate settings

### PR DESCRIPTION
**Pull request by nik0**
- Enable audio AES filter
- Now can choose more audio in/out bitrate
  Please note the constraints:
   * Filtering AES, NS is available with in bitrate under or egal 16000
   * When select OPUS out birate is 48000
   * When select PCM or PCMU in bitrate shall be egal to out bitrate

- Can now control video FPS
     * I noticed that some configuration freeze the video (for example 1/1)

### CODE REVIEW

**Comment by nik0** [comment]
I didn't noticed that the copy is done file by file.
I remove the file from PR

**Comment by tssva** [comment]
Just took a look at the v4l2rtspserver-master code and that isn't how the bitrate is being applied which also matches up with what I am seeing at the actual bitrate of the mp3 stream I am receiving. Anyways not really relevant to this PR. Later today I will open an issue regarding this against v4l2rtspserver-master with details.

**Comment by nik0** [comment]
You can open an issue on the  v4l2rtspserver-master repo, or maybe correct it by yourself ....

**Comment by jmtatsch** [comment]
Works well, thanks for fixing those issues

**Comment by mr-orange** [comment]
Please see the issue #532.
Thanks.

**Pull request merged**
