### PR TITLE
Dumped Firmware 5.6.2.182

### PR DESCRIPTION
**Pull request by fabi280**
* Additionally unpacked the driverfs
* Took the config.bin from the previous fw as my dumped one contained credentials

### CODE REVIEW

**Comment by jmtatsch** [comment]
Lets hope the old config bin is compatible with fw. What the heck, at least we have some newer drivers :)

**Comment by fabi280** [comment]
> Lets hope the old config bin is compatible with you new fw. What the heck, at least we have some newer drivers :)

The config.bin is a filesystem. The files look nearly identical. They're textfiles containing some configs
image

**Comment by rah66** [comment]
> Lets hope the old config bin is compatible with you new fw. What the heck, at least we have some newer drivers :)
> 
> The config.bin is a filesystem. The files look nearly identical. They're textfiles containing some configs

How to unpack, change and pack config.bin? I need to change the value **P2p_UID=** in file .user_config

**Comment by golmatt** [comment]
Hi! Anyone knows if this version of firmware works with Xiofang S1 Mode: ISC5 MAC starting with 34:XX ?

**Pull request merged**
