### PR TITLE
Sendmail and new busy box

### PR DESCRIPTION
**Pull request by nik0**
- Don't forget to copy and change the .dist into .conf
- Tested only with gmail. Not sure some other parameter need to be changed for other email providers
- Add openssl binary
- Also update version of busybox

### CODE REVIEW

**Comment by nobet78** [comment]
nik0 Have You got openssl binary do download?

**Comment by nik0** [comment]
Yes it is included in bin folder (same branch)

**Comment by nobet78** [comment]
Got this warning:
WARNING: can't open config file: /home/osboxes/SRC/Xiaomi-Dafang-Software/libressl/_install/etc/ssl/openssl.cnf
depth=1 C = US, O = Google Trust Services, CN = Google Internet Authority G3
verify error:num=20:unable to get local issuer certificate
verify return:0

**Comment by nik0** [comment]
This is just a warning, ignore it

**Comment by EliasKotlyar** [comment]
Many thanks @nik0 !

**Pull request merged**
