### PR TITLE
create autonight.conf to fix auto night mode issue

### PR DESCRIPTION
**Pull request by cwiggs**
This PR was created as a result of this issue: https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/1145

Adding this file with the same default settings that are in the "SW night configuration" page fixes an issue where even if
auto night mode is enabled it does not seem to work.  

This also fixes an error in `/var/log/lighttpd-cgi-stderr.log` when auto night mode is enabled, the error is `cat: can't open '/system/sdcard/config/autonight.conf': No such file or directory`

If anyone has suggestions on what these settings do I'd love to add them to the file.

### CODE REVIEW

**Comment by jmtatsch** [comment]
At https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/77e3ac8b7c049f543e7a1f515e0be9aa7c0655e5/firmware_mod/www/cgi-bin/state.cgi#L44 this will make cameras with superior hw light sensor use the inferior sw auto night path.

**Comment by cwiggs** [comment]
Hm okay, sounds like it might be best to update that file to check for something different.

In the System > Video > Auto Night Mode there is a radio button for HW/SW, perhaps we can use that same method in the cgi file?  I'm not sure where those options come from though, any ideas?

**Comment by cwiggs** [comment]
Perhaps it would better to just add documentation on how to enable the SW auto night setting?

Initially it looks like when you go to the "SW night configuration" page in the gui the SW night config is enabled, but really that page is making calls to the sw night application, using the "config" or "Commandline to use".  However if you want it to persist even when you aren't on the page you have to click the "save" button and stop/start the auto night mode.

Personally I'd rather have a button that allows you to switch between SW and HW mode, although I think the radio buttons under System > Video just tell you which mode is active, it doesn't allow you to control the mode.

@jmtatsch what do you think?

**Comment by jmtatsch** [comment]
Sorry I didn't get back to you for quite some time.
After reevaluating this whole mess, i would suggest the following:

1) autonight.conf should exist by default and look like this:
AUTONIGHT_MODE="HW"
HW_PARAMETERS=""
SW_PARAMETERS="-S -j 3 -w 3 -1 1200000 -2 930000,14,10 -3 3000,17,8"

2) https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/88cf55cce1126634effb99d0698bde6c2a378192/firmware_mod/www/cgi-bin/action.cgi#L421 and the following functions have to be changed to toggle HW->SW->HW in autonight.conf

3) https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/66d42918df1bbd1f2fedd7b08fb9c6aa879e02fc/firmware_mod/www/cgi-bin/system_video.cgi#L214 has to be changed to read from a function like the next one

4) https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/88cf55cce1126634effb99d0698bde6c2a378192/firmware_mod/www/cgi-bin/state.cgi#L43 needs to be adjusted

5) UI in https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/66d42918df1bbd1f2fedd7b08fb9c6aa879e02fc/firmware_mod/www/cgi-bin/system_video.cgi#L214 must be adjusted

6) saver for software autonight must be adjusted

Could you please rework your pull request accordingly?

**Pull request closed without merging**
